import mongoose, { Schema } from 'mongoose';

const BookingSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true },
    serviceId: { type: Schema.Types.ObjectId, ref: 'Service', required: true },
    categoryId: {
      type: Schema.Types.ObjectId,
      ref: 'Category',
      required: true,
    },
    day: { type: String, required: true },
    date: { type: String, required: true },
    time: { type: String, required: true },
    endDate: { type: String },
    endTime: { type: String },
    bookingMode: {
      type: String,
      enum: ['request', 'instant'],
      default: 'request',
    },
    status: {
      type: String,
      enum: [
        'draft',
        'pending',
        'confirmed',
        'accepted',
        'completed',
        'declined',
        'cancelled',
        'refunded',
        'no_show',
        'disputed',
      ],
      default: 'draft',
    },
    location: { type: String, required: true },
    hotelName: { type: String },
    childCount: { type: Number },
    childAges: [{ type: String }],
    emergencyContactName: { type: String },
    emergencyContactPhone: { type: String },
    allergies: { type: String },
    medicalNotes: { type: String },
    instructions: { type: String },
    timezone: { type: String },
    holdExpiresAt: { type: Date },
    responseDeadline: { type: Date },
    reminderSent: { type: Boolean, default: false },
    disputeReason: { type: String },
    disputeReportedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    disputeResolutionNotes: { type: String },
    disputeResolvedBy: { type: Schema.Types.ObjectId, ref: 'User' },
    disputeResolvedAt: { type: Date },
    pricingSnapshot: {
      hourlyRate: Number,
      durationHours: Number,
      serviceSubtotal: Number,
      bookingFeePercent: Number,
      bookingFeeMinimum: Number,
      trustedBookingFee: Number,
      currency: String,
      membershipType: String,
      membershipPrice: Number,
      payNowTotal: Number,
      payPartnerLater: Number,
    },
  },
  { timestamps: true },
);

const Booking = mongoose.model('Booking', BookingSchema);
export default Booking;
